[package]
name = "p3-commit"
description = "Plonky3 is a toolkit for implementing polynomial IOPs (PIOPs), such as PLONK and STARKs."
version = "0.1.7-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
test-utils = ["dep:p3-dft"]

[dependencies]
p3-challenger = { path = "../challenger", version = "0.1.7-succinct" }
p3-field = { path = "../field", version = "0.1.7-succinct" }
p3-matrix = { path = "../matrix", version = "0.1.7-succinct" }
p3-util = { path = "../util", version = "0.1.7-succinct" }

itertools = "0.12.0"
serde = { version = "1.0", default-features = false }

# for testing
p3-dft = { path = "../dft", optional = true, version = "0.1.7-succinct" }

[dev-dependencies]
p3-baby-bear = { path = "../baby-bear", version = "0.1.7-succinct" }
p3-dft = { path = "../dft", version = "0.1.7-succinct" }
rand = "0.8.5"
