[package]
name = "p3-matrix"
description = "Plonky3 is a toolkit for implementing polynomial IOPs (PIOPs), such as PLONK and STARKs."
version = "0.2.0-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = { path = "../field", version = "0.2.0-succinct" }
p3-maybe-rayon = { path = "../maybe-rayon", version = "0.2.0-succinct" }
p3-util = { path = "../util", version = "0.2.0-succinct" }
itertools = "0.12.0"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1.37"

[dev-dependencies]
criterion = "0.5.1"
p3-mersenne-31 = { path = "../mersenne-31", version = "0.2.0-succinct" }

[[bench]]
name = "transpose_benchmark"
path = "benches/transpose_benchmark.rs"
harness = false
