[package]
name = "p3-dft"
description = "Plonky3 is a toolkit for implementing polynomial IOPs (PIOPs), such as PLONK and STARKs."
version = "0.2.0-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = { path = "../field", version = "0.2.0-succinct" }
p3-matrix = { path = "../matrix", version = "0.2.0-succinct" }
p3-maybe-rayon = { path = "../maybe-rayon", version = "0.2.0-succinct" }
p3-util = { path = "../util", version = "0.2.0-succinct" }
tracing = "0.1.37"

[dev-dependencies]
p3-baby-bear = { path = "../baby-bear", version = "0.2.0-succinct" }
p3-goldilocks = { path = "../goldilocks", version = "0.2.0-succinct" }
p3-mersenne-31 = { path = "../mersenne-31", version = "0.2.0-succinct" }
criterion = "0.5.1"
rand = "0.8.5"

[[bench]]
name = "fft"
harness = false
