[package]
name = "p3-rescue"
description = "Plonky3 is a toolkit for implementing polynomial IOPs (PIOPs), such as PLONK and STARKs."
version = "0.2.0-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
gcd = "2.3.0"
itertools = "0.12.0"
modinverse = "0.1.1"
num = "0.4.0"
num-integer = "0.1.45"
p3-field = { path = "../field", version = "0.2.0-succinct" }
p3-mds = { path = "../mds", version = "0.2.0-succinct" }
p3-symmetric = { path = "../symmetric", version = "0.2.0-succinct" }
p3-util = { path = "../util", version = "0.2.0-succinct" }
rand = "0.8.5"
sha3 = "0.10.8"

[dev-dependencies]
p3-baby-bear = { path = "../baby-bear", version = "0.2.0-succinct" }
p3-goldilocks = { path = "../goldilocks", version = "0.2.0-succinct" }
p3-mersenne-31 = { path = "../mersenne-31", version = "0.2.0-succinct" }
criterion = "0.5.1"

[[bench]]
name = "rescue"
harness = false
