[package]
name = "p3-symmetric"
description = "Plonky3 is a toolkit for implementing polynomial IOPs (PIOPs), such as PLONK and STARKs."
version = "0.2.0-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = { path = "../field", version = "0.2.0-succinct" }
itertools = "0.12.0"
serde = { version = "1.0", default-features = false, features = ["alloc"] }
