[package]
name = "p3-lde"
description = "Plonky3 is a toolkit for implementing polynomial IOPs (PIOPs), such as PLONK and STARKs."
version = "0.2.0-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = { path = "../field", version = "0.2.0-succinct" }
p3-matrix = { path = "../matrix", version = "0.2.0-succinct" }
p3-util = { path = "../util", version = "0.2.0-succinct" }
