[package]
name = "p3-circle"
description = "Plonky3 is a toolkit for implementing polynomial IOPs (PIOPs), such as PLONK and STARKs."
version = "0.2.0-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-challenger = { path = "../challenger", version = "0.2.0-succinct" }
p3-commit = { path = "../commit", version = "0.2.0-succinct" }
p3-dft = { path = "../dft", version = "0.2.0-succinct" }
p3-field = { path = "../field", version = "0.2.0-succinct" }
p3-matrix = { path = "../matrix", version = "0.2.0-succinct" }
p3-maybe-rayon = { path = "../maybe-rayon", version = "0.2.0-succinct" }
p3-util = { path = "../util", version = "0.2.0-succinct" }

tracing = "0.1.37"
itertools = "0.12.0"

[dev-dependencies]
p3-mds = { path = "../mds", version = "0.2.0-succinct" }
p3-mersenne-31 = { path = "../mersenne-31", version = "0.2.0-succinct" }
p3-merkle-tree = { path = "../merkle-tree", version = "0.2.0-succinct" }
p3-poseidon = { path = "../poseidon", version = "0.2.0-succinct" }
p3-symmetric = { path = "../symmetric", version = "0.2.0-succinct" }

hashbrown = "0.14.3"
rand = "0.8.5"
